### PR TITLE
V2.0.0 Preview

### PR DESCRIPTION
**Pull request by mattclarke**
* Spring cleaning (requirements, copyrights etc.)
* Removed Python 2 support
* Added system tests
* Added scripts to make it easier to run from source

### CODE REVIEW

**Comment by mattclarke** [comment]
@DominicOram: Hi Dom, would you mind trying this PR out with your stuff to see if I have broken anything for you.
Shout if you need any help or if you find anything amiss.
I'm assuming you are on at least 3.6...

**Comment by DominicOram** [comment]
Sure, when would you like it merged by? Are ESS making more extensive use of it now? I believe CLF are also using it. It may be worth a meeting at some point to share ideas about lewis going forward?

Yes, we're on 3.8.

**Comment by mattclarke** [comment]
Somewhen this week would be good, if possible, but it isn't urgent.

**Comment by DominicOram** [comment]
Ok, I'm quite busy this week, I'll take a look Thursday/Friday

**Comment by DominicOram** [comment]
Gave it a go today. The backdoor didn't work with the IOC Test Framework out the box but worked ok manually. Most likely something odd we're doing. I'll take another look Tuesday

**Comment by DominicOram** [comment]
Works fine, backdoor seems to be slightly slower but I updated to Python 3 at the same time so likely due to that. I'm happy for this to be merged and pushed.

**Comment by mattclarke** [comment]
Thanks Dom.

**Comment by DominicOram** [comment]
No worries, when are you planning to release?

**Comment by mattclarke** [comment]
Probably next week, just need to find a few hours to do it in.
It will probably be v1.4 rather than 2.0 - I don't think the changes justify going to 2.0

**Pull request merged**
